### ISSUE TITLE
Typo in status text - Rebuidling Kernel ... and error message

### ISSUE THREAD

**Issue by sunefalck** [thelamehacker/cleanmymac#5]
Rebuilding XPC cache...
Rebuilding CoreDuet...
Rebuilding launch services...
Flushing DNS cache and restarting mDNS...
Clearing BootCache...
Updating dyld cache...
Rebuidling Kernel extension cache...
Running daily, weekly and monthly maintenance scripts...

All done! Your mac is now squeaky clean!

Minor spelling error - otherwise the script run without any problems

Regards Sune Falck

**Comment by sunefalck** [comment]
cleaners/00_meta.sh

"arugment" should be "argument" in the following row
echo "You have passed an invalid arugment

Regards Sune Falck

**Comment by thelamehacker** [comment]
Thank you. Fixed.
